### ISSUE TITLE
Fix cross references in RFC 3810 for tables in sections 7.4.1 and 7.4.2

### ISSUE THREAD

**Issue by bkhabs** [ietf-wg-pim/igmp-mld-bis#10]
RFC 3810 makes multiple references like "see Tables 7.4.1 and 7.4.2", but the tables do not have actual assigned numbers. The tables are in sections 7.4.1 and 7.4.2. We need to fix these cross-references to either reference the section numbers or create labels for all figures and tables in the document.

**Comment by bkhabs** [comment]
Updated all references to the Tables to be references to the respective sections of the document.

**Comment by mmcbride7** [comment]
Hi good bis people,

Are you all ready for me to start an adoption call for
draft-mcast-pim-3810bis-00/draft-mcast-pim-3376bis-00?

mike

**Comment by bkhabs** [comment]
Hey Mike,
     Yes, I think you can start adoption calls at any point.

Thanks,
Brian

**Comment by bkhabs** [comment]
Updated cross-references were submitted with the -00 WG drafts.
