### ISSUE TITLE
RFC 3376 - Incorporate Erratum 4375

### ISSUE THREAD

**Issue by bkhabs** [ietf-wg-pim/igmp-mld-bis#3]
https://www.rfc-editor.org/errata/eid4375

**Comment by anujbudhiraja** [comment]
I would suggest changing the 8.12 like below as this will be in sync with 8.13 also.

8.12. Older Version Querier Present Timeout

   The Older Version Querier Interval is the time-out for transitioning
   a host back to IGMPv3 mode once an older version query is heard.
   When an older version query is received, hosts set their Older
   Version Querier Present Timer to Older Version Querier Interval.

   This value MUST be ((the Robustness Variable) times (the Query
   Interval)) plus (one Query Response Interval).

**Comment by anujbudhiraja** [comment]
Suggested changes:

8.12. Older Version Querier Present Interval

   The Older Version Querier Present Interval is the time-out for transitioning
   a host back to IGMPv3 mode once an older version query is heard.
   When an older version query is received, hosts set their Older
   Version Querier Present Timer to Older Version Querier Interval.

   It is RECOMMENDED to use the default values for calculating the interval value. 
   Default value of the Robustness variable is 2 and the Query interval is 125 seconds. 

   This value SHOULD be ((the Robustness Variable) times (the Query
   Interval)) plus (1/10)th of the (maximum response time).

**Comment by bkhabs** [comment]
Text has been incorporated into the draft.
