### ISSUE TITLE
RFC 3810 - Add text identifying the use of MLD for link-local multicast addresses

### ISSUE THREAD

**Issue by bkhabs** [ietf-wg-pim/igmp-mld-bis#4]
https://www.rfc-editor.org/errata/eid5977

**Comment by femi-komolafe** [comment]
[Section 6](https://datatracker.ietf.org/doc/html/rfc3810#section-6) in RFC 3810  states: 
"No MLD messages are ever sent regarding neither the link-scope all-nodes multicast address, nor any multicast address of scope 0 (reserved) or 1 (node-local)."  
And there appears to be no text in the RFC explicitly clarifying how scope 2 (link-local) are handled.

In comparison, [Section 1](https://datatracker.ietf.org/doc/html/rfc3590#section-1) in RFC 3590   states:
"In addition, MLD also requires nodes to send MLD Report messages when joining any IPv6 multicast group (except the All-Nodes address and addresses of scope less than 2)." 
Suggesting that MLD messages should be sent for addresses of scope 2.

So the point raised in https://www.rfc-editor.org/errata/eid5977 seems valid; it would be beneficial to explicitly state that MLD messages can be sent for link-local addresses too.

**Comment by bkhabs** [comment]
Text has been incorporated into the draft.
